### ISSUE TITLE
release date?

### ISSUE THREAD

**Issue by tarek360** [phosphor-icons/phosphor-flutter#1]
Hi there,

Thank you for `phosphor-icons`!

Will it be ready soon as a Flutter package?

**Comment by rektdeckard** [comment]
Hey, thanks for the interest and sorry for the delay in getting back to you. This port was mostly the effort of @rurickdev. As a non Flutter user, I don't think I have intentions of finishing and publishing it unless someone steps in to help. That being said, contributions are welcome!

**Comment by DominicHW** [comment]
Hey folks. I'm a programmer/graphic designer and would be interested in helping out in my spare time to get this port out.

Cheers!

**Comment by afkcodes** [comment]
@rektdeckard I can try this but i will be needing some help from the font side. i will be needing a ttf file.

**Comment by rektdeckard** [comment]
The icon font is available on the [phosphor-icons/phosphor-icons](https://www.github.com/phosphor-icons/phosphor-icons/tree/master/src%2Ffont) package, and is also included in the asset kit on our website.

I would request that anything you build is extensible and can be easily updated when new icons are added. We rely on code generation to create icon components for the rest of our framework-specific libraries (see the `/bin` folder in most projects).

**Comment by afkcodes** [comment]
here is what i have tried : https://github.com/afkcodes/flutter_phosphor_icons
haven't updated the readme also have to look how to go about duotone.

**Comment by rektdeckard** [comment]
Duotone is going to be a challenge, I remember running into that limitation before. The two solutions we came up with were to pivot and use the `flutter_svg` package to implement this as an SVG library (which breaks compatibility with lots of things depending on flutter `Icon`s) or to use one of several libraries that converts an SVG into Skia graphics primitives.

Alternately, I would be ok with leaving Duotone out for now, and releasing with the other 5 weights.

**Comment by afkcodes** [comment]
the other five weights are already done then i have to update the readme and example app and then we can go ahead.

**Comment by rektdeckard** [comment]
If you don't mind, please fork this repo and make a PR back here, so we can keep it under one roof! I'll add you as a maintainer.

**Comment by afkcodes** [comment]
sure thing will do in the morning. Thanks.

**Comment by afkcodes** [comment]
just asking will it be a issue if i keep it on my github.

**Comment by rektdeckard** [comment]
No problem here! I would prefer to be the publisher on pub.dev if that's okay, simply to make the release process easier and to make this an officially supported first-party package. We can create a Phosphor Icons publisher account, and you can be authorized there as well.

**Comment by afkcodes** [comment]
sure then lets keep it on my account and please go ahead with the account creation, meanwhile i will update readme and example app also look into the possibility for duotone icons.

**Comment by rurickdev** [comment]
Hey everyone, I'm the main flutter developer, sorry for the late answer, I don't have enough free time, the package is practically working, and ready for the first release (just need to update to latest icon font) 
The duo tone icons are not available yet because the is no don't door that side, but I have been researching about covering SVGs to Paint paths automatically to use in flutter.

**Comment by rektdeckard** [comment]
@rurickdev excellent to have you back, and thanks for putting the last leg of work in! Reviewing now, and have the example app running beautifully.

**Comment by rektdeckard** [comment]
@afkcodes in light of the similarities of your approach to Rurick's, I think we're going to start from their implementation as a base.
