### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by CodeDoctorDE** [phosphor-icons/phosphor-flutter#6]
Can you please update the package to 1.3.1 and add a link to the pub page in the readme?

**Comment by bernaferrari** [comment]
Please

**Comment by rektdeckard** [comment]
Expect an update by Monday!

**Comment by CodeDoctorDE** [comment]
Maybe it would be nice if this can be automated using GitHub action's

**Comment by rektdeckard** [comment]
[v1.3.1](https://pub.dev/packages/phosphor_flutter/) is now live. I'll look into automating this.

**Comment by CodeDoctorDE** [comment]
https://stackoverflow.com/a/58468828 maybe an idea to automate this?

**Comment by CodeDoctorDE** [comment]
It would be nice if phosphoricons for flutter would be updated to 2.0.

For automation I would add a github action on the main repository that clones this repository on release, run the script, commit it and push it automatically

**Comment by rektdeckard** [comment]
I was planning on getting to the Flutter update tomorrow, and tend to trust nothing when it comes to generation of our icon font 😅 but PRs are welcome.
